name: lastu_pdate_chat_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  audioplayers: ^6.5.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  file_picker: ^10.3.6
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_contacts: ^1.1.9+2
  flutter_launcher_icons: ^0.14.4
  flutter_sound: ^9.28.0
  fluttertoast: ^9.0.0
  geolocator: ^14.0.2
  get_it: ^9.1.0
  http: ^1.6.0
  huawei_push: ^6.14.0+300
  image_picker: ^1.2.1
  intl: ^0.20.2
  lottie: ^3.3.2
  path: ^1.9.1
  path_provider: ^2.1.5
  pdfx: ^2.9.2
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  supabase_flutter: ^2.10.3
  url_launcher: ^6.3.2
  uuid: ^4.5.2
  webview_flutter: ^4.13.0
  zego_uikit_prebuilt_call: ^4.21.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/3.png
  android: true
  ios: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/3.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
